# Generated by Django 2.2.8 on 2020-08-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_attendance_total_lectures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Constraint',
        ),
    ]
