# Generated by Django 2.2.8 on 2020-08-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20200816_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='is_attendance',
            field=models.BooleanField(default=False),
        ),
    ]
